config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "books#index"
  resources :genres
  
  get 'search', to: 'search#index'
  resources :authors
  resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  def name
    self.first_name + " " + self.last_name
  end

  include PgSearch::Model
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  monetize :price_cents, as: :price
  include PgSearch::Model
  
  pg_search_scope :search,
                  against: [:title, :description, :author_id, :genre_id],
                  using: { tsearch: {dictionary: "english"} },
                  associated_against: { 
                    author: [:first_name, :last_name],
                    genre: [:name]
                  }

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books
  include PgSearch::Model
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_genres, :set_authors

  private
    def set_genres
      @genres = Genre.all
    end
    def set_authors
      @authors = Author.all
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    if params[:query].blank?
      @books = Book.order(title: :asc, created_at: :desc)
    else
      @books = Book.order(title: :asc, created_at: :desc).where(genre: params[:query])
    end
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :genre_id, :img_url, :author_id, :price_cents, :price)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
      @books = Book.search(params[:query])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <div class="album py-5 bg-body-tertiary">
    <div class="container">
    <h1>All books by <%= author.name %></h1>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% author.books.each do |book| %>
          <%= render book %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to "Show this author", author %>
    </p>
  <% end %>
</div>

<%= link_to "New author", new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <div class="col">
    <div class="card shadow-sm">
      <img src='<%= book.img_url %>' class="img-thumbnail" >
      <div class="card-body">
        <p class="card-text">
          <strong>Назва:</strong>
          <%= book.title %>
        </p>
        <p>
          <strong>Автор:</strong>
          <%= link_to book.author.name, book.author %>
        </p>
        <p>
          <strong>Жанр:</strong>
          <%= book.genre.name %>
        </p>
        
        <small class="text-body-secondary">
            <p>
              <strong>Ціна:</strong>
              <%= book.price %>
            </p>
        </small>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Детальніше", book %></button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Купити</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.collection_select :genre_id, Genre.all, :id, :name, prompt: true %>
  </div>

  <div>
    <%= form.label :img_url, style: "display: block" %>
    <%= form.url_field :img_url %>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.collection_select :author_id, Author.all, :id, :name, prompt: true %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="album py-5 bg-body-tertiary">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @books.each do |book| %>
        <%= render book %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="album py-5 bg-body-tertiary">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <%= render "form", book: @book %>
      <br>
      <div>
        <%= link_to "Back to books", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="album py-5 bg-body-tertiary">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2">
      <div id="<%= dom_id @book %>">
        <div class="col">
          <div class="card shadow-sm">
            <img src='<%= @book.img_url %>' class="img-thumbnail" >
            <div class="card-body">
              <p class="card-text">
                <strong>Назва:</strong>
                <%= @book.title %>
              </p>
              <p>
                <strong>Автор:</strong>
                <%= @book.author.name%>
              </p>
              <p>
                <strong>Жанр:</strong>
                <%= @book.genre.name %>
              </p>
              <p>
                <strong>Опис:</strong>
                <%= @book.description %>
              </p>
              <small class="text-body-secondary">
                  <p>
                    <strong>Ціна:</strong>
                    <%= @book.price %>
                  </p>
              </small>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Купити</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
  
  <div class="album py-5 bg-body-tertiary">
    <div class="container">
    <p>
      <strong>Name:</strong>
      <%= genre.name %>
    </p>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% genre.books.each do |book| %>
          <%= render book %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Show this genre", @genre %> |
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Genres</h1>

<div id="genres">
  <% @genres.each do |genre| %>
    <%= render genre %>
    <p>
      <%= link_to "Show this genre", genre %>
    </p>
  <% end %>
</div>

<%= link_to "New genre", new_genre_path %>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @genre %>

<div>
  <%= link_to "Edit this genre", edit_genre_path(@genre) %> |
  <%= link_to "Back to genres", genres_path %>

  <%= button_to "Destroy this genre", @genre, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-body-secondary py-5">
  <div class="container">
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to "New book", new_book_path, class: 'nav-link px-2 link-secondary' %></li>
        <li><%= link_to "All books", books_path, class: 'nav-link px-2 link-secondary' %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Genres</a>
          <ul class="dropdown-menu">
            <% @genres.each do |genre|%>
              <li><%= link_to genre.name, books_path(genre: genre), class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Authors</a>
          <ul class="dropdown-menu">
            <% @authors.each do |author|%>
              <li><%= link_to author.name, books_path(author: author), class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <div class="form-outline">
        <%= form_with url: search_path, method: :get, class: "col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3", role: "search" do |form| %>
          <%= form.text_field :query, class: "form-control", placeholder: "Search..." %>
        <% end %>
      </div>

      <div class="dropdown text-end">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
        </a>
        <ul class="dropdown-menu text-small">
          <li><a class="dropdown-item" href="#">New project...</a></li>
          <li><a class="dropdown-item" href="#">Settings</a></li>
          <li><a class="dropdown-item" href="#">Profile</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %> 
      <div> Welcome <%= current_user.email %> </div> 
      <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
    <% else %>
      <%= button_to "Sign in", new_user_session_path %> 
    <% end %>
    <%= render "layouts/header"%>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/search/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="album py-5 bg-body-tertiary">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @books.each do |book| %>
        <%= render book %>
      <% end %>
    </div>
  </div>
</div>